# Site
repository: omkardeshpande23994/omkardeshpande23994.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Omkar Deshpande
title: Senior Business Analyst
email: omkar.deshpande23994@gmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: omkardeshpande-23994 # LinkedIn username
github_username: omkardeshpande23994 # GitHub username

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
