# Site
repository: omkardeshpande/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Omkar Deshpande
title: Senior Analytics Consultant
email: omkar.deshpande23994@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: omkardeshpande-23994
github_username: omkardeshpande

# Additional icon links
additional_links:
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://linkedin.com/in/omkardeshpande-23994

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  Experienced Senior Analytics Consultant with a strong background in data analytics, business intelligence, and risk management. Skilled in process optimization, dashboard development, and stakeholder engagement to drive data-driven decision-making and efficiency.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Wells Fargo, India
        sub_title: Senior Analytics Consultant
        caption: July 2024 – Present
        description: | 
          - **Loudspeaker Dashboard Ownership**: Managed and streamlined weekly analytics reporting, providing insights across topics and teams.
          - **JIRA Reporting Dashboard Development**: Developed a JIRA case tracking dashboard, visualizing team efficiency and Agile progress.
          - **Process Optimization**: Improved data processes to cut execution time and reduce manual interventions.
          - **Tableau Reporting**: Developed optimized data sources, reducing report refresh times on Tableau Server.
          - **Risk Management**: Aligned reporting workflows with compliance standards.

      - layout: left
        title: Data Axle, India (Client: American Express)
        sub_title: Senior Business Systems Analyst
        caption: June 2021 – July 2024
        description: | 
          - **Process Improvement & Quality Control**: Spearheaded BAU and monthly processing for Cox and Carrier ID projects.
          - **Dashboard Development**: Created production dashboards for MDI and AMEX, streamlining decision-making.
          - **Operational Efficiency Gains**: Automated QC checklists and alerts, improving SLA timelines.
          - **Client Engagement**: Managed end-to-end communication, ensuring timely updates and project success.

      - layout: left
        title: ZS Associates, India
        sub_title: Business Technology Analyst
        caption: November 2020 – May 2021
        description: | 
          - **Tableau Dashboards for BMS Eliquis**: Developed dashboards that enabled strategic decisions for brand management.
          - **Data Quality Assurance**: Performed in-depth data analysis and quality checks for accuracy.
          - **Client-Centric Reporting**: Provided timely analysis and recommendations for business strategy.

      - layout: left
        title: Zensar Technologies, India
        sub_title: Data Analyst
        caption: October 2016 – March 2019
        description: | 
          - **Client Relationship Management**: Primary contact for APJGC clients, ensuring project alignment.
          - **Data Analysis and Reporting**: Utilized SQL, QlikView, and Tableau for customized reporting and analysis.
          - **Process Optimization**: Streamlined workflows for case management and change requests.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Munster Technological University, Cork, Ireland
        caption: 2019 – 2020
        sub_title: Master of Science (M.S.) - Artificial Intelligence
      - layout: left
        title: Savitribai Phule Pune University, Pune, India
        caption: 2012 – 2016
        sub_title: Bachelor of Engineering (B.E.) - Computer Science

  - title: Skills
    layout: list
    content:
      - layout: top-middle
        title: Data Visualization & Reporting
        description: |
          - Tableau, Advanced Excel (Pivot Tables, Macros)
      - layout: top-middle
        title: Data Management & Quality Control
        description: |
          - SQL, Data Hygiene, Statistical Analysis, AWS Athena, S3
      - layout: top-middle
        title: Programming Languages
        description: |
          - Python (NumPy, Pandas)
      - layout: top-middle
        title: Project Management
        description: |
          - JIRA, Kanban, Agile & Scrum
      - layout: top-middle
        title: Process Automation
        description: |
          - Power Query, Excel Macros
      - layout: top-middle
        title: Documentation & Stakeholder Communication
        description: |
          - FRD, BRD, CRD, GAP Analysis, RTM
      - layout: top-middle
        title: ETL & Database Tools
        description: |
          - Talend, Oracle SQL Developer
      - layout: top-middle
        title: Cloud & Version Control
        description: |
          - AWS CloudWatch, Git

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
